import { Platform } from 'react-native'

export const BOTTOM_BAR_HEIGHT = Platform.OS === 'ios'
  ? 70
  : 50

export const CATEGORIES = [
  { name: 'American', id: 'tradamerican' },
  { name: 'Asian Fusion', id: 'asianfusion' },
  { name: 'Australian', id: 'australian' },
  { name: 'Bars', id: 'bars' },
  { name: 'Brazilian', id: 'brazilian' },
  { name: 'Breakfast & Brunch', id: 'breakfast_brunch' },
  { name: 'Buffets', id: 'buffets' },
  { name: 'Burgers', id: 'burgers' },
  { name: 'Chinese', id: 'chinese' },
  { name: 'Creperies', id: 'creperies' },
  { name: 'Foodstands', id: 'foodstands' },
  { name: 'French', id: 'french' },
  { name: 'Gastropubs', id: 'gastropubs' },
  { name: 'Gluten Free', id: 'gluten_free' },
  { name: 'Greek', id: 'greek' },
  { name: 'Himalayan', id: 'himalayan' },
  { name: 'Hot Dogs', id: 'hotdog' },
  { name: 'Hungarian', id: 'hungarian' },
  { name: 'Indian', id: 'indpak' },
  { name: 'Irish', id: 'irish' },
  { name: 'Italian', id: 'italian' },
  { name: 'Japanese', id: 'japanese' },
  { name: 'Kebab', id: 'kebab' },
  { name: 'Korean', id: 'korean' },
  { name: 'Latin', id: 'latin' },
  { name: 'Raw Food', id: 'raw_food' },
  { name: 'Mexican', id: 'mexican' },
  { name: 'Pakistani', id: 'pakistani' },
  { name: 'Parma', id: 'parma' },
  { name: 'Persian', id: 'persian' },
  { name: 'Pizza', id: 'pizza' },
  { name: 'Russian', id: 'russian' },
  { name: 'Salad', id: 'salad' },
  { name: 'Sandwiches', id: 'sandwiches' },
  { name: 'Seafood', id: 'seafood' },
  { name: 'Soup', id: 'soup' },
  { name: 'Spanish', id: 'spanish' },
  { name: 'Steak', id: 'steak' },
  { name: 'Sushi', id: 'sushi' },
  { name: 'Syrian', id: 'syrian' },
  { name: 'Tapas', id: 'tapasmallplates' },
  { name: 'Thai', id: 'thai' },
  { name: 'Turkish', id: 'turkish' },
  { name: 'Vegan', id: 'vegan' },
  { name: 'Vegetarian', id: 'vegetarian' },
  { name: 'Vietnamese', id: 'vietnamese' },
  { name: 'Waffles', id: 'waffles' },
]
